### PR TITLE
⚠️ CONFLICT! Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request: CONFLICT #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-docker.git`](https://github.com/cisagov/skeleton-docker.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Take ownership of this pull request by removing any other assignees.

1. Clone the repository locally, and reapply the merge:

    ```console
    git clone git@github.com:cisagov/domain-manager-api.git domain-manager-api
    cd domain-manager-api
    git remote add skeleton https://github.com/cisagov/skeleton-docker.git
    git remote set-url --push skeleton no_push
    git switch develop
    git checkout -b lineage/skeleton --track origin/develop
    git pull skeleton HEAD
    git status
    ```

1. Review the changes displayed by the `status` command.  Fix any conflicts and
   possibly incorrect auto-merges.

1. After resolving each of the conflicts, `add` your changes to the
   branch, `commit`, and `push` your changes:

    ```console
    git add .github/CODEOWNERS .gitignore README.md docker-compose.yml tag.sh 
    git commit
    git push --force --set-upstream origin lineage/skeleton
    ```

    Note that you may _append_ to the default merge commit message
    that git creates for you, but *please do not delete the existing
    content*.  It provides useful information about the merge that is
    being performed.

1. Wait for all the automated tests to pass.

1. Check the "Everything is cool" checkbox below:

    - [x] ✌️ The conflicts in this pull request have been resolved.

1. Mark this draft pull request "Ready for review".

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Comment by itsmostafa** [comment]
FYI: I could not get this hook to work. I tried revs 1.0.5 and v1.0.6 It fails without any detailed errors:
```yaml
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
```

Here's the pre-commit check result for it:
```
Shell Syntax Check.......................................................Failed
- hook id: shell-lint
- exit code: 1
```

**Comment by jsf9k** [comment]
> FYI: I could not get this hook to work. I tried revs 1.0.5 and v1.0.6 It fails without any detailed errors:
> 
> ```yaml
>   - repo: https://github.com/detailyang/pre-commit-shell
>     rev: 1.0.5
>     hooks:
>       - id: shell-lint
> ```
> 
> Here's the pre-commit check result for it:
> 
> ```
> Shell Syntax Check.......................................................Failed
> - hook id: shell-lint
> - exit code: 1
> ```

Is it failing because `shfmt` is not installed?  @mcdonnnj are you able to assist?

**Comment by itsmostafa** [comment]
> > FYI: I could not get this hook to work. I tried revs 1.0.5 and v1.0.6 It fails without any detailed errors:
> > ```yaml
> >   - repo: https://github.com/detailyang/pre-commit-shell
> >     rev: 1.0.5
> >     hooks:
> >       - id: shell-lint
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here's the pre-commit check result for it:
> > ```
> > Shell Syntax Check.......................................................Failed
> > - hook id: shell-lint
> > - exit code: 1
> > ```
> 
> Is it failing because `shfmt` is not installed? @mcdonnnj are you able to assist?

I previously had an shfmt error too. I installed `shfmt` and fixed it. But still failing at `shell-lint` hook

**Comment by jsf9k** [comment]
> > > FYI: I could not get this hook to work. I tried revs 1.0.5 and v1.0.6 It fails without any detailed errors:
> > > ```yaml
> > >   - repo: https://github.com/detailyang/pre-commit-shell
> > >     rev: 1.0.5
> > >     hooks:
> > >       - id: shell-lint
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Here's the pre-commit check result for it:
> > > ```
> > > Shell Syntax Check.......................................................Failed
> > > - hook id: shell-lint
> > > - exit code: 1
> > > ```
> > 
> > 
> > Is it failing because `shfmt` is not installed? @mcdonnnj are you able to assist?
> 
> I previously had an shfmt error too. I installed `shfmt` and fixed it. But still failing at `shell-lint` hook

Is this an old PR that would also need `shellcheck`?  I seem to recall that we switched from one to the other at one point.

**Comment by itsmostafa** [comment]
> > > > FYI: I could not get this hook to work. I tried revs 1.0.5 and v1.0.6 It fails without any detailed errors:
> > > > ```yaml
> > > >   - repo: https://github.com/detailyang/pre-commit-shell
> > > >     rev: 1.0.5
> > > >     hooks:
> > > >       - id: shell-lint
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Here's the pre-commit check result for it:
> > > > ```
> > > > Shell Syntax Check.......................................................Failed
> > > > - hook id: shell-lint
> > > > - exit code: 1
> > > > ```
> > > 
> > > 
> > > Is it failing because `shfmt` is not installed? @mcdonnnj are you able to assist?
> > 
> > 
> > I previously had an shfmt error too. I installed `shfmt` and fixed it. But still failing at `shell-lint` hook
> 
> Is this an old PR that would also need `shellcheck`? I seem to recall that we switched from one to the other at one point.



> > > > FYI: I could not get this hook to work. I tried revs 1.0.5 and v1.0.6 It fails without any detailed errors:
> > > > ```yaml
> > > >   - repo: https://github.com/detailyang/pre-commit-shell
> > > >     rev: 1.0.5
> > > >     hooks:
> > > >       - id: shell-lint
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Here's the pre-commit check result for it:
> > > > ```
> > > > Shell Syntax Check.......................................................Failed
> > > > - hook id: shell-lint
> > > > - exit code: 1
> > > > ```
> > > 
> > > 
> > > Is it failing because `shfmt` is not installed? @mcdonnnj are you able to assist?
> > 
> > 
> > I previously had an shfmt error too. I installed `shfmt` and fixed it. But still failing at `shell-lint` hook
> 
> Is this an old PR that would also need `shellcheck`? I seem to recall that we switched from one to the other at one point.

Sorry @jsf9k looks like i fixed it. just forgot to add `shfmt-py` to reqs-test in addition to installing it locally. It passes now. just failing else where. working through it

**Comment by mcdonnnj** [comment]
> 
> 
> > > FYI: I could not get this hook to work. I tried revs 1.0.5 and v1.0.6 It fails without any detailed errors:
> > > ```yaml
> > >   - repo: https://github.com/detailyang/pre-commit-shell
> > >     rev: 1.0.5
> > >     hooks:
> > >       - id: shell-lint
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Here's the pre-commit check result for it:
> > > ```
> > > Shell Syntax Check.......................................................Failed
> > > - hook id: shell-lint
> > > - exit code: 1
> > > ```
> > 
> > 
> > Is it failing because `shfmt` is not installed? @mcdonnnj are you able to assist?
> 
> I previously had an shfmt error too. I installed `shfmt` and fixed it. But still failing at `shell-lint` hook

@itsmostafa If you have a correctly configured `lint` job [it will install `shfmt`](https://github.com/cisagov/skeleton-generic/blob/1b5cd2546b1b4df0cf106eaa617c691b91cfa9e6/.github/workflows/build.yml#L81-L86). The `.github/build.yml` in this branch is missing a number of elements that can be found in the current `cisagov/skeleton-generic`'s `.github/build.yml`.

Your last two commits fail because of the `isort` hook as seen [here](https://github.com/cisagov/domain-manager-api/runs/3594011223#step:13:43) and [here](https://github.com/cisagov/domain-manager-api/runs/3594001768#step:13:42). If you are using `pre-commit` locally I am unsure on how you have conflicting results compared to when it's run in a GitHub Actions runner.

When run on my local development environment I see the same issue:

```console
$ pre-commit run --all-files
Check for case conflicts.................................................Passed
Check that executables have shebangs.....................................Passed
Check JSON...............................................................Passed
Check for merge conflicts................................................Passed
Check Toml...........................................(no files to check)Skipped
Check Xml............................................(no files to check)Skipped
Debug Statements (Python)................................................Passed
Detect AWS Credentials...................................................Passed
Detect Private Key.......................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Pretty format JSON.......................................................Passed
Fix requirements.txt.....................................................Passed
Trim Trailing Whitespace.................................................Passed
markdownlint.............................................................Passed
prettier.................................................................Passed
yamllint.................................................................Passed
validate pre-commit manifest.........................(no files to check)Skipped
Format bash shell scripts................................................Passed
Shell Syntax Check.......................................................Passed
bandit (tests tree)......................................................Passed
bandit (everything else).................................................Passed
black....................................................................Passed
flake8...................................................................Passed
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing /<redacted>/domain-manager-api/tests/views/test_application_views.py

mypy.....................................................................Passed
pyupgrade................................................................Passed
Ansible-lint.............................................................Passed
Terraform fmt........................................(no files to check)Skipped
Validate docker-compose files............................................Passed
Packer Validate..........................................................Passed
Packer Format........................................(no files to check)Skipped
```

Please note I removed the `shfmt-py` requirement because I have it installed directly through Golang.

Lastly as this appears to be a Python project I am unclear on why you are using [cisagov/skeleton-generic](https://github.com/cisagov/skeleton-generic) as your Lineage upstream instead of [cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library).

**Comment by itsmostafa** [comment]
> > > > FYI: I could not get this hook to work. I tried revs 1.0.5 and v1.0.6 It fails without any detailed errors:
> > > > ```yaml
> > > >   - repo: https://github.com/detailyang/pre-commit-shell
> > > >     rev: 1.0.5
> > > >     hooks:
> > > >       - id: shell-lint
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Here's the pre-commit check result for it:
> > > > ```
> > > > Shell Syntax Check.......................................................Failed
> > > > - hook id: shell-lint
> > > > - exit code: 1
> > > > ```
> > > 
> > > 
> > > Is it failing because `shfmt` is not installed? @mcdonnnj are you able to assist?
> > 
> > 
> > I previously had an shfmt error too. I installed `shfmt` and fixed it. But still failing at `shell-lint` hook
> 
> @itsmostafa If you have a correctly configured `lint` job [it will install `shfmt`](https://github.com/cisagov/skeleton-generic/blob/1b5cd2546b1b4df0cf106eaa617c691b91cfa9e6/.github/workflows/build.yml#L81-L86). The `.github/build.yml` in this branch is missing a number of elements that can be found in the current `cisagov/skeleton-generic`'s `.github/build.yml`.
> 
> Your last two commits fail because of the `isort` hook as seen [here](https://github.com/cisagov/domain-manager-api/runs/3594011223#step:13:43) and [here](https://github.com/cisagov/domain-manager-api/runs/3594001768#step:13:42). If you are using `pre-commit` locally I am unsure on how you have conflicting results compared to when it's run in a GitHub Actions runner.
> 
> When run on my local development environment I see the same issue:
> 
> ```
> $ pre-commit run --all-files
> Check for case conflicts.................................................Passed
> Check that executables have shebangs.....................................Passed
> Check JSON...............................................................Passed
> Check for merge conflicts................................................Passed
> Check Toml...........................................(no files to check)Skipped
> Check Xml............................................(no files to check)Skipped
> Debug Statements (Python)................................................Passed
> Detect AWS Credentials...................................................Passed
> Detect Private Key.......................................................Passed
> Fix End of Files.........................................................Passed
> Mixed line ending........................................................Passed
> Pretty format JSON.......................................................Passed
> Fix requirements.txt.....................................................Passed
> Trim Trailing Whitespace.................................................Passed
> markdownlint.............................................................Passed
> prettier.................................................................Passed
> yamllint.................................................................Passed
> validate pre-commit manifest.........................(no files to check)Skipped
> Format bash shell scripts................................................Passed
> Shell Syntax Check.......................................................Passed
> bandit (tests tree)......................................................Passed
> bandit (everything else).................................................Passed
> black....................................................................Passed
> flake8...................................................................Passed
> isort....................................................................Failed
> - hook id: isort
> - files were modified by this hook
> 
> Fixing /<redacted>/domain-manager-api/tests/views/test_application_views.py
> 
> mypy.....................................................................Passed
> pyupgrade................................................................Passed
> Ansible-lint.............................................................Passed
> Terraform fmt........................................(no files to check)Skipped
> Validate docker-compose files............................................Passed
> Packer Validate..........................................................Passed
> Packer Format........................................(no files to check)Skipped
> ```
> 
> Please note I removed the `shfmt-py` requirement because I have it installed directly through Golang.
> 
> Lastly as this appears to be a Python project I am unclear on why you are using [cisagov/skeleton-generic](https://github.com/cisagov/skeleton-generic) as your Lineage upstream instead of [cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library).



> > > > FYI: I could not get this hook to work. I tried revs 1.0.5 and v1.0.6 It fails without any detailed errors:
> > > > ```yaml
> > > >   - repo: https://github.com/detailyang/pre-commit-shell
> > > >     rev: 1.0.5
> > > >     hooks:
> > > >       - id: shell-lint
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Here's the pre-commit check result for it:
> > > > ```
> > > > Shell Syntax Check.......................................................Failed
> > > > - hook id: shell-lint
> > > > - exit code: 1
> > > > ```
> > > 
> > > 
> > > Is it failing because `shfmt` is not installed? @mcdonnnj are you able to assist?
> > 
> > 
> > I previously had an shfmt error too. I installed `shfmt` and fixed it. But still failing at `shell-lint` hook
> 
> @itsmostafa If you have a correctly configured `lint` job [it will install `shfmt`](https://github.com/cisagov/skeleton-generic/blob/1b5cd2546b1b4df0cf106eaa617c691b91cfa9e6/.github/workflows/build.yml#L81-L86). The `.github/build.yml` in this branch is missing a number of elements that can be found in the current `cisagov/skeleton-generic`'s `.github/build.yml`.
> 
> Your last two commits fail because of the `isort` hook as seen [here](https://github.com/cisagov/domain-manager-api/runs/3594011223#step:13:43) and [here](https://github.com/cisagov/domain-manager-api/runs/3594001768#step:13:42). If you are using `pre-commit` locally I am unsure on how you have conflicting results compared to when it's run in a GitHub Actions runner.
> 
> When run on my local development environment I see the same issue:
> 
> ```
> $ pre-commit run --all-files
> Check for case conflicts.................................................Passed
> Check that executables have shebangs.....................................Passed
> Check JSON...............................................................Passed
> Check for merge conflicts................................................Passed
> Check Toml...........................................(no files to check)Skipped
> Check Xml............................................(no files to check)Skipped
> Debug Statements (Python)................................................Passed
> Detect AWS Credentials...................................................Passed
> Detect Private Key.......................................................Passed
> Fix End of Files.........................................................Passed
> Mixed line ending........................................................Passed
> Pretty format JSON.......................................................Passed
> Fix requirements.txt.....................................................Passed
> Trim Trailing Whitespace.................................................Passed
> markdownlint.............................................................Passed
> prettier.................................................................Passed
> yamllint.................................................................Passed
> validate pre-commit manifest.........................(no files to check)Skipped
> Format bash shell scripts................................................Passed
> Shell Syntax Check.......................................................Passed
> bandit (tests tree)......................................................Passed
> bandit (everything else).................................................Passed
> black....................................................................Passed
> flake8...................................................................Passed
> isort....................................................................Failed
> - hook id: isort
> - files were modified by this hook
> 
> Fixing /<redacted>/domain-manager-api/tests/views/test_application_views.py
> 
> mypy.....................................................................Passed
> pyupgrade................................................................Passed
> Ansible-lint.............................................................Passed
> Terraform fmt........................................(no files to check)Skipped
> Validate docker-compose files............................................Passed
> Packer Validate..........................................................Passed
> Packer Format........................................(no files to check)Skipped
> ```
> 
> Please note I removed the `shfmt-py` requirement because I have it installed directly through Golang.
> 
> Lastly as this appears to be a Python project I am unclear on why you are using [cisagov/skeleton-generic](https://github.com/cisagov/skeleton-generic) as your Lineage upstream instead of [cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library).

@mcdonnnj I have already fixed all issues mentioned and all tests have passed. Thanks for letting me know regarding the golang install of shfmt, I can add that instead and remove the shfmt-py package i previously just added.

Regarding the skeleton libraries you mentioned, I'm not sure why we are using one skeleton over the other as I was not involved in that decision. However, I'm assuming maybe because this project is a mixture of Python and Golang. I will reach out to a team mate regarding this if you would prefer to have the skeleton switched the python based one. I appreciate the help!

**Comment by itsmostafa** [comment]
@mcdonnnj @jsf9k this PR is ready for review. Thanks

**Review by zenine07 — APPROVED** [review]

**Pull request merged**
