### PR TITLE
feature: dm-308 upload bulk domains

### PR DESCRIPTION
**Pull request by itsmostafa**
Create the ability to create multiple domains in bulk

## 💭 Description
The new expected post body is a JSON list
```json
["domain1.com", "domain2.com", "domain3.com"]
```
the updated response will now be a list of nameservers returned:
```json
[
    {
        "domain1.com": [
            "ns-207.awsdns-25.com",
            "ns-1569.awsdns-04.co.uk",
            "ns-1140.awsdns-14.org",
            "ns-777.awsdns-33.net"
        ]
    },
    {
        "domain2.com": [
            "ns-1914.awsdns-47.co.uk",
            "ns-968.awsdns-57.net",
            "ns-308.awsdns-38.com",
            "ns-1191.awsdns-20.org"
        ]
    },
    {
        "domain3.com": [
            "ns-231.awsdns-28.com",
            "ns-888.awsdns-47.net",
            "ns-1888.awsdns-44.co.uk",
            "ns-1322.awsdns-37.org"
        ]
    }
]
```

## ✅ Checklist

- [X] My code follows the code style of this project.
- [X] My changes have been adequately tested locally.
- [X] All automated tests are passing.
- [X] I have updated/added required automated tests.
- [X] Pre-commit checks are passing.

### CODE REVIEW

**Review by zenine07 — CHANGES_REQUESTED** [review]
Not compatible with current state of the UI. If you can update this to support both lists of domain names ["domain1.com", "domain2.com", ...] and a dict {"name": "domain1.com"}, I'll approve and merge.

**Comment by itsmostafa** [comment]
> Not compatible with current state of the UI. If you can update this to support both lists of domain names ["domain1.com", "domain2.com", ...] and a dict {"name": "domain1.com"}, I'll approve and merge.

I know, was planning to link up with Dylan this morning on this

**Review by zenine07 — APPROVED** [review]
Now that frontend is in place. Tested this and works great.

**Review by zenine07 — APPROVED** [review]
After UI has been implemented. Tested this and works great!

**Pull request merged**
